### ISSUE TITLE
support config like workflow

### ISSUE THREAD

**Issue by wklken** [wklken/httptest#29]
github actions

```
jobs:
   xxxx:
     steps:
       - name: xxxxx
         run: xxxx
       - name: xxxx
         run: xxxx
```

like the `order` in [config](https://wklken.me/httptest/usage/config/) file, but more powerful
