### ISSUE TITLE
bug: multiple cases in same yaml

### ISSUE THREAD

**Issue by wklken** [wklken/httptest#62]
if got an empty case, will panic

```
request:
  method: get
  url: 'http://httpbin.org/get'
assert:
  status: ok
  statusCode: 200
  contentLength_gt: 180
  contentType: application/json
---
```
