### ISSUE TITLE
problem found

### ISSUE THREAD

**Issue by wklken** [wklken/httptest#63]
- json path/value, values contains or starts_with or regex

**Comment by wklken** [comment]
```
request:
  method: get 
  url: https://httpbin/status/302
assert:
  hasRedirect: true
```

bug: assert.hasredirect: Fail | line:23 | equal | expected=`false`(bool), actual=`true`(bool)
